#!/usr/bin/env bash
echo "== delete bucket"

if [ -z "$1" ]; then
  echo "Please provide a bucket name as an argument."
  exit 1
fi

BUCKET_NAME=$1

echo "Deleting bucket with name" $BUCKET_NAME
aws s3 rb "s3://$BUCKET_NAME"