#!/usr/bin/env bash
echo "== upload a file"

if [ -z "$1" ]; then
  echo "Please provide a bucket name as an argument."
  exit 1
fi

if [ -z "$2" ]; then
    echo "There needs to be a filename eg. ./bucket my-bucket-name filename"
    exit 1
fi

BUCKET_NAME=$1
FILE_NAME=$2
OBJECT_KEY=$(basename "$FILE_NAME")

echo "Uploading a file with filename $OBJECT_KEY at path $FILE_NAME into bucket $BUCKET_NAME"

aws s3api put-object \
--bucket $BUCKET_NAME \
--body $FILE_NAME \
--key $OBJECT_KEY